---
- name: play level variables
  hosts: local
  connection: local #Ansible is connecting to localhost
  vars:
    COURSE: JoinDevOps
    DURATION: 10HRS
    STUDENT: Nagarjuna
    TRAINER: SivaKumar
  tasks:
    - name: print the course info
      ansible.builtin.debug:
        msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Student: {{ STUDENT }}, Trainer: {{ TRAINER}}"