- name: loop
  hosts: local
  connection: local
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: "Hello {{ item }}" # item is reserved
      loop:
        - Ramesh
        - Suresh
        - Raheem
        - Shubham

# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 12-loops.yaml