- name: Install and uninstall packages
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Install services
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "nginx", state: "absent" }
        - { name: "mysql", state: "absent" }
        - { name: "zip", state: "latest" }

# Execute command
# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 14-loops-install-uninstall.yaml