- name: user creation
  hosts: local
  connection: local
  tasks:
    - name: check user exits or not
      ansible.builtin.command: id roboshop
      register: user_output
      ignore_errors: true
    
    - name: print the output
      ansible.builtin.debug:
        msg: "{{ user_output }}"
